### ISSUE TITLE
Include Windows executable?

### ISSUE THREAD

**Issue by hoechenberger** [conda-forge/libflac-feedstock#3]
Hello, thanks for your work on this feedstock! I've been wondering whether it would be possible to also include a Windows executable in the package? Currently, the Linux and macOS packages contain both the libraries and a `flac` executable. The Windows package, on the other hand, only ships with the libraries. Would it be possible to compile and bundle `flac.exe` as well?

**Comment by dschreij** [comment]
That's strange. For Windows I wrote a custom CMake script because the standard supplied makefiles do not work on this OS. Probably there is a flag that I should pass to CMake to also let it build the executable. I'll keep this on my radar and see if I can work on it if I have some spare time.

**Comment by hoechenberger** [comment]
Hello @dschreij,

I just downloaded the latest Windows package from conda-forge (https://anaconda.org/conda-forge/libflac/1.3.1/download/win-64/libflac-1.3.1-h6538335_1002.tar.bz2), and it only contains the following files:

```
x info/hash_input.json
x info/index.json
x info/files
x info/LICENSE.txt
x info/paths.json
x info/about.json
x info/git
x info/test/run_test.bat
x info/recipe/build.sh
x info/recipe/bld.bat
x info/recipe/conda_build_config.yaml
x info/recipe/meta.yaml
x info/recipe/meta.yaml.template
x Library/include/FLAC/assert.h
x Library/include/FLAC/ordinals.h
x Library/include/FLAC/export.h
x info/recipe/CMakeLists.txt
x Library/include/FLAC/callback.h
x Library/include/FLAC/all.h
x Library/include/FLAC/format.h
x Library/include/FLAC/stream_decoder.h
x Library/include/FLAC/stream_encoder.h
x Library/lib/libFLAC.lib
x Library/include/FLAC/metadata.h
x Library/bin/libFLAC.dll
```

So there's only a `DLL` in the `bin` directory.

Would be great if you could find the time to fix this :) Let me know if I can be of any help – don't know much about Windows build stuff I'm afraid, though :(

**Comment by hoechenberger** [comment]
I also realized that version 1.3.1 is outdated, the latest release is 1.3.2.

Also, see this issue with MSVC 2017: https://github.com/xiph/flac/issues/51
Maybe that's the explanation for the missing Windows executables?

**Comment by wolfv** [comment]
1.3.3 is released, and exe files are inside the windows package.
