### ISSUE TITLE
Could NOT find FLAC (missing: FLAC_LIBRARY) on Windows

### ISSUE THREAD

**Issue by martinRenou** [conda-forge/libflac-feedstock#7]
When building a cmake project that depends on libflac, I get a `Could NOT find FLAC (missing: FLAC_LIBRARY)` on Windows (Linux and OSX seems to be finding libflac correctly).

Looking at the recipe I see there is a custom CMakeList file.

I feel like this issue is related to the one in libvorbis package, I see you are listed as a maintainer @dschreij. Would you like me to try using the official CMakeList file for Windows? I'm happy to do it tonight.

**Comment by dschreij** [comment]
Sure, I'm occupied otherwise at the moment but I can add you ass a
maintainer once I have the chance?

**Comment by martinRenou** [comment]
I'll add myself to the maintainer list, if you're ok with it, when I'll make my PR. So don't bother doing it :)
